version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - freshdesk-service
      - salesforce-service
      - zendesk-service
    restart: unless-stopped

  freshdesk-service:
    build:
      context: ./freshdesk-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./freshdesk-service/.env
    restart: unless-stopped

  salesforce-service:
    build:
      context: ./salesforce-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./salesforce-service/.env
    restart: unless-stopped

  zendesk-service:
    build:
      context: ./zendesk-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./zendesk-service/.env
    restart: unless-stopped
